# -*- coding: utf-8 -*-
"""Systematic-review data for Chapter 2 (REM thesis).

Every value in this file was entered by the single reviewer from one of two
evidence bases, and from nothing else:
  (a) the OpenAlex/Crossref record retrieved on 2026-09-25 (title, abstract,
      venue, DOI) — stored in ../raw_search/*.json and dedup_records.json;
  (b) for records identified via other methods, the verification record in
      chapter2/tools/sources.py (CHAPTER2_REFERENCE_EVIDENCE_MATRIX.md).
Full texts were NOT retrievable in the review environment (publisher, arXiv and
index hosts were refused by the network policy; see
../raw_search/database_access_test_2026-09-25.txt). Where a property is not
visible in the accessible record it is coded "Not Verified", never "Yes".

Codes: Y=Yes, N=No, NR=Not Reported, NA=Not Applicable, NV=Not Verified.
Quality codes (Q1..Q10): Y, N, P (Q10 only: preprint clearly labelled), NV, NA.
"""

Y, N, NR, NA, NV = "Yes", "No", "Not Reported", "Not Applicable", "Not Verified"

# ---------------------------------------------------------------------------
# 1. Database stream: decisions for the 219 deduplicated OpenAlex records.
#    Key = record number in dedup_records.json (1-based, "R###").
#    Value = (title/abstract decision, full-text/eligibility decision,
#             exclusion reason, final status, included-study id or "")
#    Records not listed here were excluded at title/abstract with the default
#    reason given in DEFAULT_TA_REASON.
# ---------------------------------------------------------------------------
INC, EXC, NAS = "Include", "Exclude", "Not assessed"
OUT = "outside scope"
SEC = "secondary study (survey/review/SoK/tutorial)"
WPOP = "wrong population/system"
WTHR = "wrong threat"
WOUT = "wrong outcome"
ITE = "insufficient technical evidence"
DUP = "duplicate"
MAS = "outside scope (multi-agent inter-agent channel; review population is single tool-using agents)"
INF = "insufficient information (no abstract in index; full text inaccessible)"
META = "metadata conflict (record carries AgentDojo arXiv:2406.13352 DOI and authors with an unrelated derived-corpus title/abstract)"

DEFAULT_TA_REASON = OUT

DB = {
    # --- included at both stages -------------------------------------------------
    1: (INC, INC, "", "Included", "P01"),
    5: (INC, INC, "", "Included", "P02"),
    7: (INC, INC, "", "Included", "P03"),
    9: (INC, INC, "", "Included", "P04"),
    10: (INC, INC, "", "Included", "P05"),
    14: (INC, INC, "", "Included", "P06"),
    22: (INC, INC, "", "Included", "P07"),
    23: (INC, INC, "", "Included", "P08"),
    24: (INC, INC, "", "Included", "P09"),
    25: (INC, INC, "", "Included", "P10"),
    31: (INC, INC, "", "Included", "P11"),
    35: (INC, INC, "", "Included", "P12"),
    43: (INC, INC, "", "Included", "P13"),
    47: (INC, INC, "", "Included", "P14"),
    48: (INC, INC, "", "Included", "P15"),
    61: (INC, INC, "", "Included", "P16"),
    64: (INC, INC, "", "Included", "P17"),
    78: (INC, INC, "", "Included", "P18"),
    79: (INC, INC, "", "Included", "P19"),
    120: (INC, INC, "", "Included", "P20"),
    122: (INC, INC, "", "Included", "P21"),
    126: (INC, INC, "", "Included", "P22"),
    127: (INC, INC, "", "Included", "P23"),
    133: (INC, INC, "", "Included", "P24"),
    134: (INC, INC, "", "Included", "P25"),
    136: (INC, INC, "", "Included", "P26"),
    139: (INC, INC, "", "Included", "P27"),
    146: (INC, INC, "", "Included", "P28"),
    151: (INC, INC, "", "Included", "P29"),
    154: (INC, INC, "", "Included", "P30"),
    157: (INC, INC, "", "Included", "P31"),
    175: (INC, INC, "", "Included", "P32"),
    182: (INC, INC, "", "Included", "P33"),
    185: (INC, INC, "", "Included", "P34"),
    187: (INC, INC, "", "Included", "P35"),
    204: (INC, INC, "", "Included", "P36"),
    207: (INC, INC, "", "Included", "P37"),
    208: (INC, INC, "", "Included", "P38"),
    214: (INC, INC, "", "Included", "P39"),
    217: (INC, INC, "", "Included", "P40"),
    # --- passed title/abstract, excluded at eligibility --------------------------
    6: (INC, EXC, WPOP + " (RAG question-answering system without tool actions; viability demonstration only)", "Excluded", ""),
    16: (INC, EXC, META, "Excluded (AgentDojo assessed via other-methods record S15)", ""),
    21: (INC, EXC, ITE + " (position paper: design positions without method or evaluation)", "Excluded", ""),
    63: (INC, EXC, WOUT + " (observability taxonomy; no threat model, security method or evaluation)", "Excluded", ""),
    218: (INC, EXC, INF, "Excluded", ""),
    # --- excluded at title/abstract (reason other than default) ------------------
    2: (EXC, NAS, SEC, "Excluded", ""), 3: (EXC, NAS, SEC, "Excluded", ""),
    8: (EXC, NAS, SEC, "Excluded", ""), 11: (EXC, NAS, MAS, "Excluded", ""),
    12: (EXC, NAS, SEC, "Excluded", ""), 13: (EXC, NAS, SEC, "Excluded", ""),
    15: (EXC, NAS, SEC, "Excluded", ""),
    17: (EXC, NAS, WTHR + " (direct prompt injection in a chat game; no untrusted-content channel)", "Excluded", ""),
    18: (EXC, NAS, SEC, "Excluded", ""), 19: (EXC, NAS, SEC, "Excluded", ""),
    20: (EXC, NAS, MAS, "Excluded", ""), 26: (EXC, NAS, SEC, "Excluded", ""),
    27: (EXC, NAS, SEC, "Excluded", ""), 28: (EXC, NAS, SEC, "Excluded", ""),
    29: (EXC, NAS, MAS, "Excluded", ""),
    30: (EXC, NAS, WTHR + " (content jailbreak via query decomposition)", "Excluded", ""),
    32: (EXC, NAS, OUT + " (offensive use of LLMs, not securing agents)", "Excluded", ""),
    33: (EXC, NAS, SEC, "Excluded", ""), 34: (EXC, NAS, SEC, "Excluded", ""),
    36: (EXC, NAS, WPOP + " (multimodal LLM, not an agent)", "Excluded", ""),
    37: (EXC, NAS, SEC, "Excluded", ""), 38: (EXC, NAS, SEC, "Excluded", ""),
    39: (EXC, NAS, "official taxonomy report (not a primary study)", "Excluded", ""),
    40: (EXC, NAS, SEC, "Excluded", ""), 41: (EXC, NAS, MAS, "Excluded", ""),
    42: (EXC, NAS, SEC, "Excluded", ""), 45: (EXC, NAS, SEC, "Excluded", ""),
    46: (EXC, NAS, SEC, "Excluded", ""),
    49: (EXC, NAS, SEC, "Background source (Mao et al., 2026; cited for context only)", ""),
    50: (EXC, NAS, WPOP + " (conversational LLM application rail toolkit)", "Excluded", ""),
    51: (EXC, NAS, SEC, "Excluded", ""), 52: (EXC, NAS, SEC, "Excluded", ""),
    53: (EXC, NAS, SEC, "Excluded", ""), 55: (EXC, NAS, SEC, "Excluded", ""),
    56: (EXC, NAS, SEC, "Excluded", ""), 57: (EXC, NAS, SEC, "Excluded", ""),
    58: (EXC, NAS, SEC, "Excluded", ""), 62: (EXC, NAS, MAS, "Excluded", ""),
    67: (EXC, NAS, SEC, "Excluded", ""), 70: (EXC, NAS, SEC, "Excluded", ""),
    71: (EXC, NAS, SEC, "Excluded", ""), 72: (EXC, NAS, SEC, "Excluded", ""),
    73: (EXC, NAS, SEC, "Excluded", ""), 76: (EXC, NAS, SEC, "Excluded", ""),
    81: (EXC, NAS, SEC + " (taxonomy derived from a literature review)", "Excluded", ""),
    82: (EXC, NAS, SEC, "Background source (L. Wang et al., 2024; definition of LLM agent)", ""),
    87: (EXC, NAS, SEC, "Excluded", ""), 104: (EXC, NAS, SEC, "Excluded", ""),
    105: (EXC, NAS, SEC, "Excluded", ""), 109: (EXC, NAS, SEC, "Excluded", ""),
    113: (EXC, NAS, SEC, "Excluded", ""), 115: (EXC, NAS, SEC, "Excluded", ""),
    116: (EXC, NAS, WTHR + " (training-time deceptive backdoor; not a tool-using agent)", "Excluded", ""),
    117: (EXC, NAS, "official framework (not a primary study)", "Excluded", ""),
    118: (EXC, NAS, SEC, "Excluded", ""),
    121: (EXC, NAS, WPOP + " (LLM-as-a-judge selection, not an agent input channel)", "Excluded", ""),
    123: (EXC, NAS, SEC, "Excluded", ""), 124: (EXC, NAS, SEC, "Excluded", ""),
    125: (EXC, NAS, SEC, "Excluded", ""), 128: (EXC, NAS, MAS, "Excluded", ""),
    129: (EXC, NAS, WTHR + " (fine-tuning backdoor; outside the runtime-injection threat model)", "Excluded", ""),
    130: (EXC, NAS, SEC, "Excluded", ""), 131: (EXC, NAS, SEC, "Excluded", ""),
    132: (EXC, NAS, SEC, "Excluded", ""),
    138: (EXC, NAS, WTHR + " (content jailbreak response filtering)", "Excluded", ""),
    140: (EXC, NAS, SEC, "Background source (Yu et al., 2025; component view of agent threats)", ""),
    145: (EXC, NAS, SEC, "Excluded", ""), 147: (EXC, NAS, SEC, "Excluded", ""),
    149: (EXC, NAS, WTHR + " (non-adversarial contextual-privacy norms)", "Excluded", ""),
    150: (EXC, NAS, SEC, "Excluded", ""), 152: (EXC, NAS, SEC, "Excluded", ""),
    155: (EXC, NAS, SEC, "Excluded", ""), 156: (EXC, NAS, SEC, "Excluded", ""),
    162: (EXC, NAS, MAS, "Excluded", ""), 163: (EXC, NAS, SEC, "Excluded", ""),
    164: (EXC, NAS, SEC, "Excluded", ""), 167: (EXC, NAS, SEC, "Excluded", ""),
    169: (EXC, NAS, SEC, "Excluded", ""), 170: (EXC, NAS, SEC, "Excluded", ""),
    174: (EXC, NAS, WPOP + " (LLM fraud-inducement robustness; no agent tool use)", "Excluded", ""),
    176: (EXC, NAS, WOUT + " (banking chatbot case study without security evaluation)", "Excluded", ""),
    181: (EXC, NAS, SEC, "Excluded", ""), 183: (EXC, NAS, SEC, "Excluded", ""),
    184: (EXC, NAS, OUT + " (financial modelling crews; no security problem)", "Excluded", ""),
    186: (EXC, NAS, OUT + " (banking conversational agent; no security problem)", "Excluded", ""),
    189: (EXC, NAS, SEC, "Excluded", ""), 191: (EXC, NAS, SEC, "Excluded", ""),
    195: (EXC, NAS, SEC, "Excluded", ""), 201: (EXC, NAS, SEC, "Excluded", ""),
    202: (EXC, NAS, SEC, "Excluded", ""), 203: (EXC, NAS, SEC, "Excluded", ""),
    206: (EXC, NAS, SEC, "Excluded", ""),
    209: (EXC, NAS, WTHR + " (hallucination mitigation)", "Excluded", ""),
    210: (EXC, NAS, DUP + " (preprint of IsolateGPT; peer-reviewed NDSS 2025 version R204 retained)", "Excluded", ""),
    212: (EXC, NAS, SEC, "Excluded", ""),
    213: (EXC, NAS, OUT + " (embodied robots; discrimination/violence in physical tasks)", "Excluded", ""),
    215: (EXC, NAS, SEC, "Excluded", ""),
}

# ---------------------------------------------------------------------------
# 2. Other-methods stream: the 70 sources of the previous integrated Chapter 2
#    (itself built by known-item searching and backward citation checking of
#    the thesis corpus, verified 16–25 Sep 2026). Records whose same study was
#    retrieved by the database search are removed as cross-stream duplicates.
# ---------------------------------------------------------------------------
OM_CROSS_DUP = {  # S-id -> database record that represents the same study
    "S01": 82, "S04": 140, "S05": 187, "S09": 136, "S10": 120, "S11": 139,
    "S14": 122, "S19": 61, "S30": 214, "S33": 1, "S67": 49,
}
OM_INCLUDED = {  # S-id -> included-study id
    "S08": "P41", "S12": "P42", "S13": "P43", "S15": "P44", "S16": "P45",
    "S17": "P46", "S21": "P47", "S22": "P48", "S24": "P49", "S25": "P50",
    "S26": "P51", "S27": "P52", "S28": "P53", "S29": "P54", "S31": "P55",
    "S32": "P56", "S34": "P57", "S35": "P58", "S36": "P59", "S37": "P60",
    "S38": "P61", "S39": "P62", "S40": "P63", "S41": "P64", "S42": "P65",
    "S43": "P66", "S44": "P67", "S45": "P68", "S46": "P69", "S64": "P70",
    "S65": "P71",
}
OM_BACKGROUND = {  # not included studies; cited only for definitions/context
    "S02": "fails I2 (agent capability paper; cited for the reason-act loop)",
    "S03": "fails I2 (tool-use capability paper; cited for learned tool calling)",
    "S06": "official practitioner taxonomy (terminology only)",
    "S07": WPOP + " (pre-agent GPT-3 applications; cited as historical origin of prompt injection)",
    "S20": WPOP + " (conversation-level content classifier; cited as input/output-filter family)",
    "S68": "official regulation (EU AI Act; regulatory context only)",
}
OM_FOUNDATIONAL = [  # methodological/foundational sources (criterion I6 second clause)
    "S18", "S23", "S47", "S48", "S49", "S50", "S51", "S52", "S53", "S54",
    "S55", "S56", "S57", "S58", "S59", "S60", "S61", "S62", "S63", "S69", "S70",
]
OM_EXCLUDED = {"S66": "withdrawn preprint (FinVault; cannot serve as evidence)"}

# ---------------------------------------------------------------------------
# 3. Included studies: extraction (21 columns) and appraisal (Q1..Q10).
# ---------------------------------------------------------------------------
def st(**k):
    return k

STUDIES = [
# ======================= database stream =======================
st(id="P01", src="R001 (=S33)", cite="F. Jia et al. (2025)", title="The Task Shield: Enforcing task alignment to defend against indirect prompt injection in LLM agents", year=2025, venue="ACL 2025 (long), doi:10.18653/v1/2025.acl-long.1435", role="Defense",
   agent="Tool-using conversational LLM agent", threat="Indirect prompt injection", entry="External data returned by tools", obs="Each instruction and tool call",
   runtime=Y, context=Y, behav=NR, tool=Y, multi=NV, prov=NR, dec=Y, mit=NV, bench="AgentDojo", fin=NR,
   metrics="Attack success rate (ASR); task utility", result="ASR 2.07% with utility 69.79% on GPT-4o; outperforms existing defenses (authors)", limit="LLM-based alignment judgement; one benchmark reported in the abstract",
   q="Y Y Y NV Y Y Y NV Y Y", verif="FULLY VERIFIED", prior=True),
st(id="P02", src="R005", cite="Z. Wang et al. (2025)", title="AgentVigil: Automatic black-box red-teaming for indirect prompt injection against LLM agents", year=2025, venue="Findings of EMNLP 2025, doi:10.18653/v1/2025.findings-emnlp.1258", role="Attack",
   agent="LLM agents (tool and web)", threat="Indirect prompt injection (automated, black-box)", entry="Contextual information consumed by the agent", obs="Agent task outcome",
   runtime=NA, context=Y, behav=NA, tool=Y, multi=NV, prov=NA, dec=NA, mit=NA, bench="AgentDojo; VWA-adv", fin=NR,
   metrics="Attack success rate", result="71% and 70% success against o3-mini and GPT-4o agents; nearly double handcrafted baselines; transfers across tasks and models", limit="Attack study; defense results only summarised in abstract",
   q="Y Y Y NV Y Y Y NV Y Y", verif="FULLY VERIFIED", prior=False),
st(id="P03", src="R007", cite="Wen et al. (2025)", title="Defending against indirect prompt injection by instruction detection", year=2025, venue="Findings of EMNLP 2025, doi:10.18653/v1/2025.findings-emnlp.1060", role="Defense",
   agent="LLM-integrated application (RAG)", threat="Indirect prompt injection", entry="Retrieved external content", obs="Model hidden states and gradients for an input",
   runtime=Y, context=Y, behav=NR, tool=NR, multi=NR, prov=NR, dec=Y, mit=NR, bench="BIPIA", fin=NR,
   metrics="Detection accuracy; ASR", result="Detection accuracy 99.60% in-domain and 96.90% out-of-domain; ASR reduced to 0.03% on BIPIA", limit="Requires access to model internals (hidden states, gradients); not evaluated on tool-using agents in the abstract",
   q="Y Y Y Y Y Y NV NV Y Y", verif="FULLY VERIFIED", prior=False),
st(id="P04", src="R009", cite="C. Huang et al. (2026)", title="Model Context Protocol threat modeling and analysis of vulnerabilities to prompt injection with tool poisoning", year=2026, venue="Journal of Cybersecurity and Privacy 6(3), 84, doi:10.3390/jcp6030084", role="Threat analysis",
   agent="MCP clients/hosts connecting assistants to tools", threat="Tool poisoning (instructions in tool metadata)", entry="Tool metadata", obs="Client validation behaviour",
   runtime=NA, context=Y, behav=NV, tool=Y, multi=NR, prov=NR, dec=NA, mit=NV, bench="Seven MCP clients (empirical comparison); STRIDE/DREAD threat model", fin=NR,
   metrics="Qualitative comparison of client validation", result="Tool poisoning identified as the most prevalent client-side vulnerability; most tested clients showed issues from insufficient static validation and parameter visibility; layered defenses proposed (not evaluated)", limit="Proposed defenses (incl. behavioural anomaly detection) not evaluated",
   q="Y Y Y NV Y NV NA NV NA Y", verif="FULLY VERIFIED", prior=False),
st(id="P05", src="R010", cite="Johnson et al. (2025)", title="The dangers of indirect prompt injection attacks on LLM-based autonomous web navigation agents: A demonstration", year=2025, venue="EMNLP 2025 System Demonstrations, doi:10.18653/v1/2025.emnlp-demos.55", role="Attack",
   agent="Web-navigation agent (BrowserGym, Llama-3.1)", threat="Indirect prompt injection (universal adversarial triggers, GCG)", entry="Web page HTML / accessibility tree", obs="Agent actions on web pages",
   runtime=NA, context=Y, behav=NA, tool=Y, multi=NV, prov=NA, dec=NA, mit=NA, bench="Real websites (unspecified in abstract)", fin=NR,
   metrics="Attack success (qualitative in abstract)", result="High success rates reported qualitatively, including credential exfiltration and forced ad clicks", limit="Demonstration paper; no figures in the abstract",
   q="Y Y Y Y NV NV NV NV NV Y", verif="FULLY VERIFIED", prior=False),
st(id="P06", src="R014", cite="Zhong et al. (2025)", title="RTBAS: Defending LLM agents against prompt injection and privacy leakage", year=2025, venue="arXiv preprint, arXiv:2502.08966", role="Defense",
   agent="Tool-based agent system", threat="Prompt injection; privacy leakage", entry="Tool outputs / external content", obs="Each tool call and its data dependencies",
   runtime=Y, context=Y, behav=NR, tool=Y, multi=NV, prov=Y, dec=Y, mit=Y, bench="AgentDojo", fin=NR,
   metrics="Attacks prevented; utility loss under attack", result="Prevents all targeted attacks with 2% utility loss under attack; asks for user confirmation only when integrity/confidentiality cannot be ensured", limit="Preprint; dependency screeners use LM-as-a-judge and attention saliency",
   q="Y Y Y NV Y Y NV NV Y P", verif="FULLY VERIFIED", prior=False),
st(id="P07", src="R022", cite="P. Wang, Li, & Tian (2026)", title="Reframing LLM agent security as an agent-human interaction problem", year=2026, venue="arXiv preprint, arXiv:2605.24309", role="Analysis",
   agent="Production agent systems and security plugins", threat="General agent security", entry=NA, obs="Deployed security mechanisms",
   runtime=NA, context=NA, behav=NA, tool=NA, multi=NA, prov=NA, dec=NA, mit=NA, bench="59 papers, 21 production systems, 26 plugins (Apr 2026)", fin=NR,
   metrics="Adoption counts", result="Policy specification, runtime approval and scope configuration adopted by 14, 15 and 16 of 21 systems; intent anchoring and trust labeling (academic focus) have zero production deployment; approval fatigue vs. autonomy trade-off", limit="Position-driven analysis; preprint",
   q="Y NV Y NV Y NA NA NV Y P", verif="FULLY VERIFIED", prior=False),
st(id="P08", src="R023", cite="F. Wu, Cecchetti, & Xiao (2024)", title="System-level defense against indirect prompt injection attacks: An information flow control perspective", year=2024, venue="arXiv preprint, arXiv:2409.19091", role="Defense",
   agent="LLM system planning multi-step operations", threat="Indirect prompt injection", entry="Any untrusted source feeding the planner", obs="Planning inputs and structured plans",
   runtime=Y, context=Y, behav=NR, tool=Y, multi=Y, prov=Y, dec=Y, mit=Y, bench="Case studies and benchmarks (unnamed in abstract)", fin=NR,
   metrics="Not verified", result="Formal models of existing and f-secure LLM systems; security monitor filters untrusted input into planning; robust security with preserved functionality claimed (no figures in abstract)", limit="Preprint; quantitative results not verified",
   q="Y Y Y Y NV NV NV NV NV P", verif="FULLY VERIFIED", prior=False),
st(id="P09", src="R024", cite="Fu et al. (2024)", title="Imprompter: Tricking LLM agents into improper tool use", year=2024, venue="arXiv preprint, arXiv:2410.14923", role="Attack",
   agent="Production LLM agents (Mistral LeChat, ChatGLM, Llama)", threat="Optimised obfuscated adversarial prompts causing improper tool use", entry="Adversarial prompt text", obs="Tool invocation (e.g., markdown exfiltration)",
   runtime=NA, context=Y, behav=NA, tool=Y, multi=NR, prov=NA, dec=NA, mit=NA, bench="Production agents", fin=NR,
   metrics="End-to-end attack success", result="Information-exfiltration attack on Mistral LeChat with nearly 80% end-to-end success; transfers to production agents", limit="Requires model weights for optimisation; preprint",
   q="Y Y Y NV Y Y NV NV Y P", verif="FULLY VERIFIED", prior=False),
st(id="P10", src="R025", cite="Patil et al. (2024)", title="GoEX: Perspectives and designs towards a runtime for autonomous LLM applications", year=2024, venue="arXiv preprint, arXiv:2404.06921", role="Design",
   agent="Autonomous LLM applications executing actions", threat="Incorrect or unsafe LLM-generated actions (non-adversarial)", entry=NA, obs="Executed action",
   runtime=Y, context=NR, behav=NR, tool=Y, multi=NR, prov=NR, dec=NV, mit=Y, bench=NA, fin=NR,
   metrics=NA, result="Open-source runtime (GoEX) supporting post-facto validation through undo and damage confinement", limit="Design/perspective paper; no quantitative evaluation in the abstract",
   q="Y NV Y Y NA NA NA NV NA P", verif="FULLY VERIFIED", prior=False),
st(id="P11", src="R031", cite="J. Lin et al. (2026)", title="VIGIL: Defending LLM agents against tool-stream injection via verify-before-commit", year=2026, venue="ACL 2026 (long), doi:10.18653/v1/2026.acl-long.443", role="Defense",
   agent="LLM agents in open environments", threat="Tool-stream injection (manipulated tool metadata and runtime feedback)", entry="Tool metadata and tool feedback", obs="Speculative action before commit",
   runtime=Y, context=Y, behav=NR, tool=Y, multi=NV, prov=NR, dec=Y, mit=Y, bench="SIREN (959 tool-stream injection cases; introduced)", fin=NR,
   metrics="ASR; utility under attack", result="Reduces ASR by over 22% vs. dynamic defenses and more than doubles utility under attack vs. static baselines", limit="Abstract obtained only via search-engine text (index record has no abstract)",
   q="Y Y Y NV Y Y Y NV Y Y", verif="PARTIALLY VERIFIED", prior=False),
st(id="P12", src="R035", cite="E. Li et al. (2026)", title="ACE: A security architecture for LLM-integrated app systems", year=2026, venue="NDSS 2026, doi:10.14722/ndss.2026.230352", role="Defense",
   agent="LLM-integrated app system (system LLM invoking third-party apps)", threat="Malicious apps; indirect prompt injection; planning/execution integrity and availability", entry="Third-party apps and their outputs", obs="Abstract plan, concrete plan and execution",
   runtime=Y, context=Y, behav=NR, tool=Y, multi=Y, prov=Y, dec=Y, mit=Y, bench="InjecAgent; ASB; new attacks; LangChain Tool Usage suite (utility)", fin=NR,
   metrics="Security against attack suites; utility", result="Secure against InjecAgent and ASB IPI attacks and new attacks; demonstrates new attacks against IsolateGPT", limit="No figures in abstract",
   q="Y Y Y NV Y NV Y NV NV Y", verif="FULLY VERIFIED", prior=False),
st(id="P13", src="R043", cite="T. Liu et al. (2023)", title="Demystifying RCE vulnerabilities in LLM-integrated apps", year=2023, venue="arXiv preprint, arXiv:2309.02926", role="Threat analysis",
   agent="LLM-integrated frameworks/apps with code-execution tools", threat="Remote code execution through prompt injection", entry="User prompt to the application", obs="Framework call chains",
   runtime=NA, context=Y, behav=NA, tool=Y, multi=NA, prov=NA, dec=NA, mit=NA, bench="11 frameworks; LLM-integrated apps", fin=NR,
   metrics="Vulnerabilities found/confirmed", result="20 vulnerabilities in 11 frameworks (19 RCE, 1 arbitrary file read/write); 17 confirmed; 11 CVEs", limit="Preprint; framework-level rather than agent-runtime",
   q="Y Y Y NV Y Y NA NV Y P", verif="FULLY VERIFIED", prior=False),
st(id="P14", src="R047", cite="X. Jia et al. (2026)", title="SkillJect: Effectively automating skill-based prompt injection for skill-enabled agents", year=2026, venue="arXiv preprint, arXiv:2602.14211", role="Attack",
   agent="Skill-enabled LLM agents", threat="Poisoned skills (supply-chain prompt injection)", entry="Skill instructions and helper scripts", obs="Execution traces",
   runtime=NA, context=Y, behav=NA, tool=Y, multi=NV, prov=NA, dec=NA, mit=NA, bench="Skill-enabled platforms, backends and attack categories (unnamed)", fin=NR,
   metrics="Attack effectiveness (no figures in abstract)", result="Outperforms naive direct injection and prior manual skill-injection attacks", limit="No figures in abstract; preprint",
   q="Y Y Y NV NV NV Y NV NV P", verif="FULLY VERIFIED", prior=False),
st(id="P15", src="R048", cite="Wei et al. (2026)", title="ClawSafety: \"Safe\" LLMs, unsafe agents", year=2026, venue="arXiv preprint, arXiv:2604.01438", role="Benchmark",
   agent="Personal agents with elevated local privileges (OpenClaw)", threat="Prompt injection via skill files, emails and web pages", entry="Skill files; emails; web pages", obs="Action traces in sandboxed workspaces",
   runtime=NA, context=Y, behav=NA, tool=Y, multi=NV, prov=NA, dec=NA, mit=NA, bench="120 scenarios; 2,520 sandboxed trials; five LLMs; three frameworks", fin="No (finance is one of five professional domains)",
   metrics="ASR", result="ASR 40%–75% across models; skill instructions more dangerous than email or web; safety depends on the full deployment stack, not the backbone alone", limit="Preprint; code/data release announced but not verified",
   q="Y Y Y NV Y Y Y NV Y P", verif="FULLY VERIFIED", prior=False),
st(id="P16", src="R061 (=S19)", cite="Chennabasappa et al. (2025)", title="LlamaFirewall: An open source guardrail system for building secure AI agents", year=2025, venue="arXiv preprint, arXiv:2505.03574", role="Defense",
   agent="AI agents", threat="Prompt injection; jailbreak; agent misalignment; insecure code", entry="Untrusted inputs; agent reasoning; generated code", obs="Inputs and chain-of-thought",
   runtime=Y, context=Y, behav=Y, tool=NV, multi=NV, prov=NR, dec=Y, mit=NV, bench=NV, fin=NR,
   metrics=NV, result="Three guardrails: PromptGuard 2 (jailbreak detector), Agent Alignment Checks (chain-of-thought auditor), CodeShield; earlier numeric claims not re-confirmed", limit="Industry preprint; numbers not verified",
   q="Y Y Y Y NV NV NV NV NV P", verif="FULLY VERIFIED (components only)", prior=True),
st(id="P17", src="R064", cite="Hasan et al. (2026)", title="Model Context Protocol (MCP) at first glance: Studying the security and maintainability of MCP servers", year=2026, venue="ACM TOSEM, doi:10.1145/3814959", role="Threat analysis",
   agent="MCP servers (tool ecosystem)", threat="Server vulnerabilities incl. MCP-specific tool poisoning", entry="Tool servers / tool descriptions", obs="Server source code",
   runtime=NA, context=NA, behav=NA, tool=Y, multi=NA, prov=NA, dec=NA, mit=NA, bench="1,899 open-source MCP servers", fin=NR,
   metrics="Vulnerability prevalence", result="Eight distinct vulnerabilities (three overlap traditional ones); 7.2% of servers with general vulnerabilities; 5.5% with MCP-specific tool poisoning", limit="Static analysis of servers; not runtime behaviour",
   q="Y Y Y NV Y Y NA NV Y Y", verif="FULLY VERIFIED", prior=False),
st(id="P18", src="R078", cite="Zhu, Zhang, et al. (2025)", title="SafeScientist: Toward risk-aware scientific discoveries by LLM agents", year=2025, venue="arXiv preprint, arXiv:2505.23559", role="Defense",
   agent="AI-scientist LLM agents", threat="High-risk or unethical tasks; adversarial attacks", entry="Task prompts; tool use; agent collaboration", obs="Prompts, agent messages and tool use",
   runtime=Y, context=Y, behav=Y, tool=Y, multi=NV, prov=NR, dec=Y, mit=Y, bench="SciSafetyBench (240 high-risk tasks; 30 tools; 120 tool-related risk tasks)", fin=NR,
   metrics="Safety performance; output quality", result="Safety performance improved by 35% vs. traditional AI-scientist frameworks without loss of output quality (authors)", limit="Preprint; refusal-oriented; scientific domain",
   q="Y Y Y NV Y NV Y NV Y P", verif="FULLY VERIFIED", prior=False),
st(id="P19", src="R079", cite="Kaptein, Khan, & Podstavnychy (2026)", title="Runtime governance for AI agents: Policies on paths", year=2026, venue="arXiv preprint, arXiv:2603.16586", role="Analysis",
   agent="AI agents", threat="Compliance-policy violations (legal, data-breach, reputational)", entry=NA, obs="Partial execution path plus proposed next action",
   runtime=Y, context=NR, behav=Y, tool=Y, multi=Y, prov=NR, dec=Y, mit=NV, bench=NA, fin=NR,
   metrics=NA, result="Formalises policies as functions of agent identity, partial path, proposed next action and organisational state to a policy-violation probability; prompts and static access control are special cases; risk calibration listed as open problem", limit="Formal framework; reference implementation discussed, not evaluated",
   q="Y Y Y NV NA NA NA Y NA P", verif="FULLY VERIFIED", prior=False),
st(id="P20", src="R120 (=S10)", cite="Zhan et al. (2024)", title="InjecAgent: Benchmarking indirect prompt injections in tool-integrated LLM agents", year=2024, venue="Findings of ACL 2024, doi:10.18653/v1/2024.findings-acl.624", role="Benchmark",
   agent="Tool-integrated LLM agents", threat="Indirect prompt injection (direct harm; data exfiltration)", entry="External content (e.g., emails, websites)", obs="Single tool response and next action",
   runtime=NA, context=Y, behav=NA, tool=Y, multi="No (short cases)", prov=NA, dec=NA, mit=NA, bench="InjecAgent: 1,054 cases, 17 user tools, 62 attacker tools; 30 agents", fin=NR,
   metrics="ASR", result="ReAct-prompted GPT-4 vulnerable 24% of the time; nearly doubles with a hacking prompt", limit="No benign-utility measure",
   q="Y Y Y NV Y Y Y NV Y Y", verif="FULLY VERIFIED", prior=False),
st(id="P21", src="R122 (=S14)", cite="Zhan et al. (2025)", title="Adaptive attacks break defenses against indirect prompt injection attacks on LLM agents", year=2025, venue="Findings of NAACL 2025, doi:10.18653/v1/2025.findings-naacl.395", role="Attack",
   agent="Tool-using LLM agents", threat="Adaptive indirect prompt injection", entry="Tool outputs / external content", obs="Agent outcome under eight defenses",
   runtime=NA, context=Y, behav=NA, tool=Y, multi=NR, prov=NA, dec=NA, mit=NA, bench="Eight IPI defenses (benchmark not named in abstract)", fin=NR,
   metrics="ASR", result="All eight defenses bypassed with ASR consistently over 50%", limit="Defense set as of 2024–25",
   q="Y Y Y NV NV Y Y NV Y Y", verif="FULLY VERIFIED", prior=False),
st(id="P22", src="R126", cite="J. Shi et al. (2026)", title="Prompt injection attack to tool selection in LLM agents (ToolHijacker)", year=2026, venue="NDSS 2026, doi:10.14722/ndss.2026.230675", role="Attack",
   agent="LLM agents with retrieval-based tool selection", threat="Malicious tool document injected into the tool library", entry="Tool library / tool documents", obs="Tool selection",
   runtime=NA, context=Y, behav=NA, tool=Y, multi=NA, prov=NA, dec=NA, mit=NA, bench="Not named in abstract", fin=NR,
   metrics="Attack effectiveness", result="Outperforms manual and automated PI attacks on tool selection; StruQ, SecAlign, known-answer detection, DataSentinel and perplexity defenses insufficient", limit="No figures in abstract",
   q="Y Y Y NV NV NV Y NV NV Y", verif="FULLY VERIFIED", prior=False),
st(id="P23", src="R127", cite="Jacob et al. (2025)", title="PromptShield: Deployable detection for prompt injection attacks", year=2025, venue="CODASPY '25 (ACM), pp. 341–352, doi:10.1145/3714393.3726501", role="Defense",
   agent="LLM-integrated applications", threat="Prompt injection", entry="Conversational and application-structured inputs", obs="Input text",
   runtime=Y, context=Y, behav=NR, tool=NR, multi=NR, prov=NR, dec=Y, mit=NR, bench="PromptShield benchmark (introduced)", fin=NR,
   metrics="Detection at low false-positive rate", result="Fine-tuned detector significantly better than prior schemes in the low-FPR regime", limit="No figures in abstract; input-level only",
   q="Y Y Y NV Y Y Y NV NV Y", verif="FULLY VERIFIED (Crossref issued-year 2024 vs. 2025 proceedings recorded)", prior=False),
st(id="P24", src="R133", cite="Y. Chen et al. (2025)", title="Defense against prompt injection attack by leveraging attack techniques", year=2025, venue="ACL 2025 (long), doi:10.18653/v1/2025.acl-long.897", role="Defense",
   agent="LLM-integrated applications", threat="Prompt injection in retrieved data", entry="Retrieved content", obs="Input prompt",
   runtime=Y, context=Y, behav=NR, tool=NR, multi=NR, prov=NR, dec=NR, mit=NR, bench="Not named in abstract", fin=NR,
   metrics="Not verified", result="Training-free defenses built by re-applying attack techniques with the original instruction; outperform existing defenses (authors)", limit="No figures in abstract; prompt-level",
   q="Y Y Y NV NV NV Y NV NV Y", verif="FULLY VERIFIED", prior=False),
st(id="P25", src="R134", cite="Y. Liu et al. (2023)", title="Prompt injection attack against LLM-integrated applications (HouYi)", year=2023, venue="arXiv preprint, arXiv:2306.05499", role="Attack",
   agent="Commercial LLM-integrated applications", threat="Black-box prompt injection", entry="Application input", obs="Application output",
   runtime=NA, context=Y, behav=NA, tool=NR, multi=NA, prov=NA, dec=NA, mit=NA, bench="36 real applications", fin=NR,
   metrics="Susceptible applications", result="31 of 36 applications susceptible; 10 vendors validated", limit="Preprint; application outputs rather than tool actions",
   q="Y Y Y NV Y Y NA NV Y P", verif="FULLY VERIFIED", prior=False),
st(id="P26", src="R136 (=S09)", cite="Greshake et al. (2023)", title="Not what you've signed up for: Compromising real-world LLM-integrated applications with indirect prompt injection", year=2023, venue="AISec '23 (ACM), pp. 79–90, doi:10.1145/3605764.3623985", role="Threat analysis",
   agent="LLM-integrated applications with retrieval/tools", threat="Indirect prompt injection", entry="Data retrieved at inference time", obs="Application behaviour",
   runtime=NA, context=Y, behav=NA, tool=Y, multi=NR, prov=NA, dec=NA, mit=NA, bench="Bing Chat; code-completion engines; GPT-4 synthetic applications", fin=NR,
   metrics="Demonstrations", result="Retrieved prompts can act like arbitrary code execution and control API calls; taxonomy of impacts (data theft, worming, contamination)", limit="Demonstrations on 2023 applications",
   q="Y Y Y NV Y NA NA NV NA Y", verif="FULLY VERIFIED", prior=False),
st(id="P27", src="R139 (=S11)", cite="H. Zhang et al. (2025)", title="Agent Security Bench (ASB): Formalizing and benchmarking attacks and defenses in LLM-based agents", year=2025, venue="ICLR 2025 (record: arXiv:2410.02644)", role="Benchmark",
   agent="LLM-based agents", threat="Direct/indirect PI, memory poisoning, Plan-of-Thought backdoor, mixed", entry="System prompt, user prompt, tool use, memory retrieval", obs="Agent outcome per stage",
   runtime=NA, context=Y, behav=NA, tool=Y, multi=Y, prov=NA, dec=NA, mit=NA, bench="10 scenarios, 10 agents, >400 tools, 27 methods, 7 metrics, 13 backbones", fin="No (finance is one of 10 scenarios)",
   metrics="ASR; utility-security metric", result="Highest average ASR 84.30%; current defenses show limited effectiveness", limit="Finance not analysed separately",
   q="Y Y Y Y Y Y Y NV Y Y", verif="FULLY VERIFIED", prior=False),
st(id="P28", src="R146", cite="B. Zhang et al. (2025)", title="Breaking agents: Compromising autonomous LLM agents through malfunction amplification", year=2025, venue="EMNLP 2025, pp. 34952–34964, doi:10.18653/v1/2025.emnlp-main.1771", role="Attack",
   agent="Autonomous tool-using LLM agents (single and multi-agent)", threat="Malfunction amplification (repetitive or irrelevant actions)", entry="Adversarial input to agent", obs="Action sequence",
   runtime=NA, context=Y, behav=Y, tool=Y, multi=Y, prov=NA, dec=NA, mit=Y, bench="Multiple scenarios (unnamed)", fin=NR,
   metrics="Failure rate", result="Failure rates above 80% in multiple scenarios; harder to detect than overtly harmful attacks; self-examination defenses proposed", limit="Defense effectiveness not quantified in abstract",
   q="Y Y Y NV NV NV NV Y Y Y", verif="FULLY VERIFIED", prior=False),
st(id="P29", src="R151", cite="Pedro et al. (2023)", title="From prompt injections to SQL injection attacks: How protected is your LLM-integrated web application?", year=2023, venue="arXiv preprint, arXiv:2308.01990", role="Attack",
   agent="LangChain-based web applications with SQL tool", threat="Prompt-to-SQL injection", entry="User prompt", obs="Generated SQL",
   runtime=NA, context=Y, behav=NA, tool=Y, multi=NA, prov=NA, dec=NA, mit=Y, bench="LangChain case study; 7 LLMs", fin=NR,
   metrics="Not verified", result="P2SQL attacks pervasive across seven LLMs; four defenses proposed as LangChain extensions", limit="Preprint; no figures in abstract",
   q="Y Y Y NV Y NV NA NV NV P", verif="FULLY VERIFIED", prior=False),
st(id="P30", src="R154", cite="Y. Zhang et al. (2024)", title="Towards action hijacking of large language model-based agent (AI²)", year=2024, venue="arXiv preprint, arXiv:2412.10807", role="Attack",
   agent="LLM-based applications generating action plans", threat="Action-plan hijacking via semantically harmless prompts", entry="User input built from application knowledge", obs="Action plan",
   runtime=NA, context=Y, behav=NA, tool=Y, multi=NV, prov=NA, dec=NA, mit=NA, bench="Three real-world applications", fin=NR,
   metrics="ASR; bypass rate", result="Average ASR 84.30% (best 99.70%); bypass 92.7% vs. common safety filters and 59.45% vs. a dedicated defense", limit="Preprint",
   q="Y Y Y NV Y Y Y NV Y P", verif="FULLY VERIFIED", prior=False),
st(id="P31", src="R157", cite="Yuan et al. (2024)", title="R-Judge: Benchmarking safety risk awareness for LLM agents", year=2024, venue="Findings of EMNLP 2024, doi:10.18653/v1/2024.findings-emnlp.79", role="Benchmark",
   agent="LLMs judging agent interaction records", threat="Behavioural safety risks in agent interactions", entry=NA, obs="Multi-turn interaction record",
   runtime=NA, context=NA, behav=Y, tool=Y, multi=Y, prov=NA, dec=NA, mit=NA, bench="569 records, 27 scenarios, 5 categories, 10 risk types; 11 LLMs", fin=NR,
   metrics="Risk-judgement accuracy", result="Best model (GPT-4o) 74.42%; other models not significantly above random", limit="Offline judgement of records, not runtime interception; abstract via search engine",
   q="Y Y Y NV Y Y Y NV Y Y", verif="PARTIALLY VERIFIED", prior=False),
st(id="P32", src="R175", cite="Castro-Maldonado et al. (2026)", title="Semantic firewalls with online ensemble learning for secure agentic RAG systems in financial chatbots", year=2026, venue="AI (MDPI) 7(3), 80, doi:10.3390/ai7030080", role="Defense",
   agent="Agentic RAG banking chatbot", threat="Customer-data protection / security (threat model not specified in abstract)", entry="User queries and retrieved content", obs="Query/response",
   runtime=Y, context=Y, behav=NR, tool=NV, multi=NR, prov=NR, dec=Y, mit=NV, bench="Public benchmarks (unnamed); ranking metrics", fin=Y,
   metrics="Ranking metrics (unspecified)", result="Empirical study of a semantic firewall with online learning in a financial agentic RAG system (no figures in abstract)", limit="Threat model and results not verifiable from the record",
   q="Y NV Y NV NV NV NV NV NV Y", verif="FULLY VERIFIED (metadata and abstract)", prior=False),
st(id="P33", src="R182", cite="Mou et al. (2026)", title="ToolSafe: Enhancing tool invocation safety of LLM-based agents via proactive step-level guardrail and feedback", year=2026, venue="Findings of ACL 2026, pp. 37125–37153, doi:10.18653/v1/2026.findings-acl.1850", role="Defense",
   agent="ReAct-style tool-using agents", threat="Unsafe tool invocations incl. prompt injection", entry="Requests and tool interaction history", obs="Each tool invocation with history",
   runtime=Y, context=Y, behav=Y, tool=Y, multi=Y, prov=NR, dec=Y, mit=Y, bench="TS-Bench (introduced)", fin=NR,
   metrics="Harmful invocations; benign completion", result="Guardrail (TS-Guard) detects unsafe invocations before execution; TS-Flow reduces harmful tool invocations by 65% on average and improves benign completion by about 10% under PI", limit="Learned guardrail (RL-trained); comparators not verified",
   q="Y Y Y NV Y Y NV NV Y Y", verif="FULLY VERIFIED", prior=False),
st(id="P34", src="R185", cite="Storf et al. (2026)", title="Constitutional black-box monitoring for scheming in LLM agents", year=2026, venue="arXiv preprint, arXiv:2603.00829", role="Defense",
   agent="Autonomous LLM agents", threat="Scheming (covert pursuit of misaligned goals)", entry=NA, obs="Externally observable trajectory",
   runtime=Y, context=NR, behav=Y, tool=Y, multi=Y, prov=NR, dec=Y, mit=NR, bench="Synthetic STRIDE/Gloom (1,000 each); 7,500 ControlArena trajectories", fin=NR,
   metrics="Monitor performance (not quantified in abstract)", result="Monitors optimised on synthetic data generalise to ControlArena; performance saturates quickly and further optimisation overfits", limit="Preprint; no figures in abstract",
   q="Y Y Y NV Y NV Y Y NV P", verif="FULLY VERIFIED", prior=False),
st(id="P35", src="R187 (=S05)", cite="Ruan et al. (2024)", title="Identifying the risks of LM agents with an LM-emulated sandbox (ToolEmu)", year=2024, venue="ICLR 2024 (record: arXiv:2309.15817)", role="Benchmark",
   agent="Tool-using LM agents", threat="Risky failures without an adversary (e.g., data leakage, financial loss)", entry=NA, obs="Emulated trajectory",
   runtime=NA, context=NA, behav=Y, tool=Y, multi=Y, prov=NA, dec=NA, mit=NA, bench="36 toolkits, 144 cases; LM-emulated tools", fin=NR,
   metrics="Failure rate; validity of flagged failures", result="68.8% of identified failures valid in human evaluation; safest agent fails 23.9% of cases", limit="Emulated tools; LM-based evaluator",
   q="Y Y Y NV Y Y Y NV Y Y", verif="FULLY VERIFIED", prior=False),
st(id="P36", src="R204", cite="Y. Wu et al. (2025)", title="IsolateGPT: An execution isolation architecture for LLM-based systems", year=2025, venue="NDSS 2025, doi:10.14722/ndss.2025.241131", role="Defense",
   agent="LLM system with third-party apps", threat="Untrusted apps; cross-app security, privacy and safety issues", entry="Third-party apps", obs="App interactions",
   runtime=Y, context=Y, behav=NR, tool=Y, multi=NR, prov=NR, dec=NV, mit=Y, bench="Attack set (unnamed)", fin=NR,
   metrics="Protection; overhead", result="Protects against many issues without loss of functionality; overhead under 30% for three-quarters of tested queries", limit="ACE (P12) reports new attacks against IsolateGPT",
   q="Y Y Y NV NV Y NV NV Y Y", verif="FULLY VERIFIED", prior=False),
st(id="P37", src="R207", cite="S. Wang, Zhu, & Li (2026)", title="Runtime policy enforcement for MCP-based LLM agents", year=2026, venue="Electronics 15(13), 2829, doi:10.3390/electronics15132829", role="Defense",
   agent="Tool-calling (MCP) LLM agents", threat="Indirect prompt injection (path traversal, exfiltration, high-frequency tool abuse)", entry="Externally retrieved data", obs="Each tool call with cross-step labels",
   runtime=Y, context=Y, behav=NR, tool=Y, multi=Y, prov=Y, dec=Y, mit=Y, bench="Controlled dataset, four attack classes; 30-task benign set; five backends; one real MCP transport", fin=NR,
   metrics="ASR; call-level false negatives; task-level false positives; overhead; tamper detection", result="ASR 40.0% to 5.0% (one backend, five repeats) vs. 35.0% for the strongest prompt-only baseline; removing cross-step label propagation raises call-level false negatives by 26.4 points; task-level false positives 30.0% (mostly by-design capability denials); sub-millisecond overhead; LLaMA-3.3-70B retains 16.7% ASR", limit="Controlled benchmark; authors frame results as mechanism-coverage evidence, not deployability",
   q="Y Y Y Y Y Y Y Y Y Y", verif="FULLY VERIFIED", prior=False),
st(id="P38", src="R208", cite="H. Li et al. (2025)", title="DRIFT: Dynamic rule-based defense with injection isolation for securing LLM agents", year=2025, venue="NeurIPS 2025 (Advances in NeurIPS 38), pp. 92825–92853, doi:10.52202/085713-2791", role="Defense",
   agent="Tool-using LLM agents", threat="Prompt injection via external tools", entry="Tool outputs; memory stream", obs="Function trajectory vs. planned trajectory",
   runtime=Y, context=Y, behav=Y, tool=Y, multi=Y, prov=NR, dec=Y, mit=Y, bench="AgentDojo; ASB; AgentDyn", fin=NR,
   metrics="Security; utility (no figures in abstract)", result="Secure Planner, Dynamic Validator (deviation, privilege and intent checks) and Injection Isolator; strong security with high utility across models (authors)", limit="No figures in abstract",
   q="Y Y Y Y Y NV NV NV NV Y", verif="FULLY VERIFIED", prior=False),
st(id="P39", src="R214 (=S30)", cite="Luo et al. (2025)", title="AGrail: A lifelong agent guardrail with effective and adaptive safety detection", year=2025, venue="ACL 2025 (long), pp. 8104–8139, doi:10.18653/v1/2025.acl-long.399", role="Defense",
   agent="LLM agents", threat="Task-specific and systemic risks", entry=NV, obs="Agent actions",
   runtime=Y, context=NV, behav=NV, tool=Y, multi=NR, prov=NR, dec=Y, mit=NV, bench=NV, fin=NR,
   metrics=NV, result="Adaptive safety checks with lifelong memory, transferred across tasks", limit="Index record lacks abstract; details from prior verification only",
   q="Y Y Y NV NV NV NV NV NV Y", verif="FULLY VERIFIED (metadata; contribution)", prior=False),
st(id="P40", src="R217", cite="Calboreanu (2026)", title="LATTICE: A governance-first architecture for authorized autonomous AI operations", year=2026, venue="Frontiers in Artificial Intelligence, doi:10.3389/frai.2026.1800407", role="Defense",
   agent="Autonomous AI agents in high-consequence operations", threat="Unauthorised actions", entry=NA, obs="Proposed action at gated execution path",
   runtime=Y, context=NR, behav=NR, tool=Y, multi=NR, prov=NR, dec=Y, mit=Y, bench="13 configurations x 10,000 runs; 21-vector adversarial suite; 4,000 trajectories across four planner families; live OS run", fin=NR,
   metrics="Verdict determinism; bypass; false-allow rate; recall; latency", result="Deterministic verdicts (zero deviations); 0/21 bypass (one-sided 95% upper bound 13.3%); a confidence-threshold baseline's false-allow rate ranged 0.03–0.998 across planners, while the reference implementation admitted zero unsafe actions at a conservative operating point that auto-allowed no action; policy evaluation p50 about 6.2 microseconds, gated enforcement p50 about 0.7 ms", limit="Single author; zero false-allow achieved at an operating point that auto-allowed no action (utility cost); architecture properties analytic under stated assumptions",
   q="Y Y Y Y Y Y Y Y Y Y", verif="FULLY VERIFIED", prior=False),
# ======================= other-methods stream =======================
st(id="P41", src="S08", cite="Y. Liu et al. (2024)", title="Formalizing and benchmarking prompt injection attacks and defenses", year=2024, venue="USENIX Security 2024, pp. 1831–1847", role="Benchmark",
   agent="LLM-integrated applications", threat="Prompt injection (formal framework)", entry="Data processed by the application", obs="Task output",
   runtime=NA, context=Y, behav=NA, tool=NA, multi=NA, prov=NA, dec=NA, mit=NA, bench="5 attacks x 10 defenses x 10 LLMs x 7 tasks", fin=NA,
   metrics=NV, result="Formal framework and systematic benchmark of attacks and defenses", limit="LLM-integrated applications, not agents",
   q="Y Y Y NV Y Y Y NV NV Y", verif="FULLY VERIFIED", prior=False),
st(id="P42", src="S12", cite="Andriushchenko et al. (2025)", title="AgentHarm: A benchmark for measuring harmfulness of LLM agents", year=2025, venue="ICLR 2025", role="Benchmark",
   agent="Tool-using LLM agents", threat="Malicious user requests (harmful multi-step tasks)", entry="User request", obs="Multi-step task execution",
   runtime=NA, context=NA, behav=NA, tool=Y, multi=Y, prov=NA, dec=NA, mit=NA, bench="110 tasks (440 augmented), 11 harm categories", fin="No (fraud is one harm category)",
   metrics=NV, result="Benchmark of harmful agentic tasks", limit="Malicious-user threat model, not indirect injection",
   q="Y Y Y NV Y NV NV NV NV Y", verif="FULLY VERIFIED", prior=True),
st(id="P43", src="S13", cite="Z. Chen et al. (2024)", title="AgentPoison: Red-teaming LLM agents via poisoning memory or knowledge bases", year=2024, venue="NeurIPS 2024", role="Attack",
   agent="RAG/memory-based agents (driving, QA, EHR)", threat="Memory/knowledge-base poisoning", entry="Long-term memory / knowledge base", obs="Retrieval and resulting action",
   runtime=NA, context=Y, behav=NA, tool=Y, multi=Y, prov=NA, dec=NA, mit=NA, bench="Three agent types", fin=NR,
   metrics="ASR; benign impact; poison rate", result="ASR at least 80% with benign impact at most 1% at poison rate below 0.1%", limit="Three agent types; not financial",
   q="Y Y Y NV Y Y NV NV Y Y", verif="FULLY VERIFIED", prior=False),
st(id="P44", src="S15", cite="Debenedetti et al. (2024)", title="AgentDojo: A dynamic environment to evaluate prompt injection attacks and defenses for LLM agents", year=2024, venue="NeurIPS 2024 Datasets & Benchmarks", role="Benchmark",
   agent="Tool-using LLM agents", threat="Indirect prompt injection via tool outputs", entry="Tool outputs", obs="Task utility and attacker-goal success per episode",
   runtime=NA, context=Y, behav=NA, tool=Y, multi=Y, prov=NA, dec=NA, mit=NA, bench="97 user tasks, 629 security test cases; Workspace, Slack, Travel, Banking suites", fin="No (generic; contains an executable Banking suite)",
   metrics="Utility; utility under attack; targeted ASR", result="Executable environment measuring utility and security jointly; evaluates defenses", limit="Limited number of distinct tasks; database record had corrupted metadata (R016)",
   q="Y Y Y NV Y Y Y NV NV Y", verif="FULLY VERIFIED", prior=True),
st(id="P45", src="S16", cite="M. Q. Li et al. (2026)", title="Taxonomy and consistency analysis of safety benchmarks for AI agents", year=2026, venue="arXiv preprint, arXiv:2605.16282", role="Analysis",
   agent="Agent safety benchmarks", threat=NA, entry=NA, obs="Benchmark rankings",
   runtime=NA, context=NA, behav=NA, tool=NA, multi=NA, prov=NA, dec=NA, mit=NA, bench="40 benchmarks", fin=NA,
   metrics="Kendall's W concordance", result="Six-axis taxonomy; no ranking concordance across benchmarks", limit="Preprint",
   q="Y NA Y NV Y Y NA NV Y P", verif="FULLY VERIFIED", prior=False),
st(id="P46", src="S17", cite="Y. Wang et al. (2026)", title="Safety, or just capability? A validity audit of agent-safety benchmarks", year=2026, venue="arXiv preprint, arXiv:2607.28685", role="Analysis",
   agent="Agent safety benchmarks", threat=NA, entry=NA, obs="Benchmark scores",
   runtime=NA, context=NA, behav=NA, tool=NA, multi=NA, prov=NA, dec=NA, mit=NA, bench="4 benchmarks; up to 22 models", fin=NA,
   metrics="F1; correlation with capability", result="Always-positive F1 baseline outranks five models; safety-capability correlation from -0.64 (n=7) to +0.02 (n=18)", limit="Preprint; small panels for some correlations",
   q="Y NA Y NV Y Y Y NV Y P", verif="FULLY VERIFIED", prior=False),
st(id="P47", src="S21", cite="Hines et al. (2024)", title="Defending against indirect prompt injection attacks with spotlighting", year=2024, venue="arXiv preprint, arXiv:2403.14720", role="Defense",
   agent="LLM systems processing untrusted documents", threat="Indirect prompt injection", entry="Untrusted documents", obs="Input text",
   runtime=Y, context=Y, behav=NA, tool=NA, multi=NA, prov=Y, dec=NA, mit=NA, bench=NV, fin=NR,
   metrics="ASR", result="ASR reduced from above 50% to below 2% with GPT-family models", limit="Decision left to the model; industry preprint",
   q="Y Y Y NV NV Y NV NV Y P", verif="FULLY VERIFIED", prior=False),
st(id="P48", src="S22", cite="S. Chen et al. (2025)", title="StruQ: Defending against prompt injection with structured queries", year=2025, venue="USENIX Security 2025", role="Defense",
   agent="LLM-integrated applications", threat="Prompt injection", entry="Data channel", obs="Model input",
   runtime=NA, context=Y, behav=NA, tool=NA, multi=NA, prov=Y, dec=NA, mit=NA, bench=NV, fin=NR,
   metrics=NV, result="Model trained to follow only prompt-channel instructions (structured instruction tuning)", limit="Requires training and model access",
   q="Y Y Y NV NV NV NV NV NV Y", verif="FULLY VERIFIED", prior=False),
st(id="P49", src="S24", cite="T. Shi et al. (2025)", title="Progent: Securing AI agents with privilege control", year=2025, venue="arXiv preprint, arXiv:2504.11703", role="Defense",
   agent="Tool-using LLM agents", threat="Indirect prompt injection; tool misuse", entry="Tool outputs", obs="Each tool call vs. privilege policy",
   runtime=Y, context=NR, behav=NR, tool=Y, multi="Yes (policy updates during task)", prov=NR, dec=Y, mit=Y, bench="AgentDojo; ASB", fin=NR,
   metrics="ASR; utility", result="ASR 39.9% to 1.0% (AgentDojo) and 70.3% to 3.9% (ASB)", limit="Binary permission decisions; depends on policy quality",
   q="Y Y Y NV Y Y Y NV Y P", verif="FULLY VERIFIED", prior=True),
st(id="P50", src="S25", cite="H. Wang, Poskitt, & Sun (2026)", title="AgentSpec: Customizable runtime enforcement for safe and reliable LLM agents", year=2026, venue="ICSE '26, doi:10.1145/3744916.3764546", role="Defense",
   agent="Code, embodied and autonomous-driving agents", threat="Unsafe actions", entry=NA, obs="Triggered action vs. rule predicate",
   runtime=Y, context=NR, behav=NR, tool=Y, multi=NV, prov=NR, dec=Y, mit=Y, bench="Code, embodied and AV settings", fin=NR,
   metrics="Unsafe executions prevented; compliance; overhead", result="Over 90% of unsafe code-agent executions prevented; all hazardous embodied actions eliminated; 100% AV compliance; millisecond overhead", limit="Requires hand-written rules; permission, not likelihood",
   q="Y Y Y NV Y Y NV NV Y Y", verif="FULLY VERIFIED", prior=True),
st(id="P51", src="S26", cite="Tsai & Bagdasarian (2025)", title="Contextual agent security: A policy for every purpose (Conseca)", year=2025, venue="HotOS '25, pp. 8–17, doi:10.1145/3713082.3730378", role="Design",
   agent="General-purpose agents", threat="Context-inappropriate actions", entry=NA, obs="Proposed action vs. task-context policy",
   runtime=Y, context=Y, behav=NR, tool=Y, multi=NR, prov=NR, dec=Y, mit=Y, bench=NA, fin=NR,
   metrics=NA, result="Just-in-time contextual policies enforced deterministically", limit="Vision paper; evaluation not verified",
   q="Y Y Y NV NA NA NA NV NA Y", verif="FULLY VERIFIED", prior=False),
st(id="P52", src="S27", cite="Debenedetti et al. (2025)", title="Defeating prompt injections by design (CaMeL)", year=2025, venue="arXiv preprint, arXiv:2503.18813 (v2)", role="Defense",
   agent="Tool-using LLM agents", threat="Prompt injection; data exfiltration", entry="Untrusted data", obs="Program control and data flow",
   runtime=Y, context=Y, behav=NR, tool=Y, multi="Yes (data flow across steps)", prov=Y, dec=Y, mit=Y, bench="AgentDojo", fin=NR,
   metrics="Tasks solved with provable security", result="77% of tasks solved with provable security vs. 84% undefended (v2; earlier version 67%)", limit="Restructures agent execution; version conflict recorded",
   q="Y Y Y NV Y Y Y NV Y P", verif="FULLY VERIFIED", prior=True),
st(id="P53", src="S28", cite="Xiang et al. (2025)", title="GuardAgent: Safeguard LLM agents via knowledge-enabled reasoning", year=2025, venue="ICML 2025, PMLR 267:68316–68342", role="Defense",
   agent="LLM agents", threat="Violations of safety guard requests", entry=NA, obs="Target agent actions",
   runtime=Y, context=NR, behav=NR, tool=Y, multi=NR, prov=NR, dec=Y, mit=Y, bench=NV, fin=NR,
   metrics=NV, result="Plans and generates guardrail code that checks target-agent actions", limit="Depends on specified guard requests",
   q="Y Y Y NV NV NV NV NV NV Y", verif="FULLY VERIFIED", prior=False),
st(id="P54", src="S29", cite="Z. Chen, Kang, & Li (2025)", title="ShieldAgent: Shielding agents via verifiable safety policy reasoning", year=2025, venue="ICML 2025, PMLR 267:8313–8344", role="Defense",
   agent="LLM agents", threat="Policy violations over trajectories", entry=NA, obs="Action trajectory",
   runtime=Y, context=NR, behav="Yes (trajectory-level)", tool=Y, multi=Y, prov=NR, dec=Y, mit=Y, bench=NV, fin=NR,
   metrics=NV, result="Probabilistic rule circuits extracted from policy documents; verifiable trajectory compliance", limit="Requires policy documents",
   q="Y Y Y NV NV NV NV NV NV Y", verif="FULLY VERIFIED", prior=True),
st(id="P55", src="S31", cite="Hua et al. (2024)", title="TrustAgent: Towards safe and trustworthy LLM-based agents", year=2024, venue="Findings of EMNLP 2024, pp. 10000–10016", role="Defense",
   agent="LLM-based agents", threat="Unsafe planning", entry=NA, obs="Plan",
   runtime="Yes (planning stage)", context=NR, behav=NR, tool="Yes (plan-level)", multi="Yes (plan-level)", prov=NR, dec=NV, mit="Yes (plan revision)", bench=NV, fin=NR,
   metrics=NV, result="Agent constitution applied pre-, in- and post-planning", limit="Planning-level only",
   q="Y Y Y NV NV NV NV NV NV Y", verif="FULLY VERIFIED", prior=False),
st(id="P56", src="S32", cite="Jiang et al. (2025)", title="Think twice before you act: Enhancing agent behavioral safety with thought correction (Thought-Aligner)", year=2025, venue="arXiv preprint, arXiv:2505.11063 (accepted to ICML 2026)", role="Defense",
   agent="LLM agents", threat="Unsafe intermediate thoughts", entry=NA, obs="Intermediate thought before action",
   runtime=Y, context=NR, behav="Yes (thought-level)", tool=NR, multi="Yes (partial)", prov=NR, dec=NV, mit="Yes (thought correction)", bench="Six LLMs", fin=NR,
   metrics="Behavioural safety rate", result="Behavioural safety from about 50% to about 90% on average across six LLMs", limit="Trained correction model",
   q="Y Y Y NV Y Y NV NV Y P", verif="FULLY VERIFIED", prior=False),
st(id="P57", src="S34", cite="Zhu, Yang, et al. (2025)", title="MELON: Provable defense against indirect prompt injection attacks in AI agents", year=2025, venue="ICML 2025, PMLR 267", role="Defense",
   agent="Tool-using LLM agents", threat="Indirect prompt injection", entry="Tool outputs", obs="Tool calls under original vs. masked re-execution",
   runtime=Y, context=NR, behav=Y, tool=Y, multi=Y, prov=NR, dec=Y, mit=NV, bench=NV, fin=NR,
   metrics=NV, result="Attack flagged when actions under masked re-execution match the original trajectory", limit="Extra execution cost",
   q="Y Y Y NV NV NV NV NV NV Y", verif="FULLY VERIFIED", prior=True),
st(id="P58", src="S35", cite="She et al. (2026)", title="Safeguarding LLM agents from misalignment through provenance analysis (ProvenanceGuard)", year=2026, venue="arXiv preprint, arXiv:2607.01236", role="Defense",
   agent="Tool-using LLM agents", threat="Misaligned tool calls incl. IPI", entry="Tool outputs; context", obs="Each tool call and its evidence provenance",
   runtime=Y, context=Y, behav="Yes (partial)", tool=Y, multi=NR, prov=Y, dec=Y, mit=Y, bench="Agent-SafetyBench; WorkBench", fin=NR,
   metrics="Error rate; intervention rate; cost; latency", result="Error 44.3% to 2.1% (Agent-SafetyBench) and 32.4% to 18.7% (WorkBench); intervention rate on aligned traces 14.5% vs. 10.9%; about 3.6 LLM calls with higher latency and cost (body details partially verified)", limit="Intervention-cost trade-off; body details via search excerpts only",
   q="Y Y Y NV Y Y Y NV Y P", verif="PARTIALLY VERIFIED", prior=True),
st(id="P59", src="S36", cite="C. L. Wang et al. (2025)", title="MI9: An integrated runtime governance framework for agentic AI", year=2025, venue="arXiv preprint, arXiv:2508.03858", role="Defense",
   agent="Agentic AI systems", threat="Emergent/unsafe agent behaviour (governance)", entry=NA, obs="Agent state and actions over time",
   runtime=Y, context=NR, behav=Y, tool=Y, multi=Y, prov=NR, dec=Y, mit="Yes (graduated containment)", bench="1,033 synthetic scenarios", fin=NV,
   metrics="Detection rate", result="99.81% detection across 1,033 synthetic scenarios (v1 abstract)", limit="Synthetic evaluation; adversarial evaluation deferred (authors, partially verified)",
   q="Y NV Y NV Y Y NV Y Y P", verif="PARTIALLY VERIFIED", prior=False),
st(id="P60", src="S37", cite="F. Li (2026)", title="OpenClaw PRISM: A zero-fork, defense-in-depth runtime security layer for tool-augmented LLM agents", year=2026, venue="arXiv preprint, arXiv:2603.11853", role="Defense",
   agent="Tool-augmented agent gateway", threat="IPI, unsafe tools, credential leakage, tampering", entry="Tool inputs/outputs; files; credentials", obs="Lifecycle hook events within a session",
   runtime=Y, context=Y, behav="Yes (session risk accumulation)", tool=Y, multi=Y, prov=NR, dec=Y, mit=Y, bench=NV, fin=NR,
   metrics=NV, result="Ten lifecycle hooks, hybrid scanning, policy controls and tamper-evident audit; session risk with TTL decay", limit="Single ecosystem; results preliminary (author)",
   q="Y Y Y NV NV NV NV Y NV P", verif="FULLY VERIFIED", prior=False),
st(id="P61", src="S38", cite="H. Wang et al. (2025)", title="ProbGuard: Probabilistic runtime monitoring for LLM agent safety (formerly Pro2Guard)", year=2025, venue="arXiv preprint, arXiv:2508.00500", role="Defense",
   agent="Autonomous-driving and embodied agents", threat="Safety-specification violations", entry=NA, obs="Abstract state sequence",
   runtime=Y, context=NR, behav=Y, tool=Y, multi=Y, prov=NR, dec=Y, mit=Y, bench="AV and embodied settings", fin="No (non-financial)",
   metrics="Warning lead time; unsafe-behaviour reduction; completion", result="Warnings up to 38.66 s ahead (AV); unsafe behaviour reduced by up to 65.37% with up to 80.4% completion (embodied); PAC-style guarantees", limit="State abstraction; non-financial",
   q="Y Y Y NV Y Y NV NV Y P", verif="FULLY VERIFIED", prior=False),
st(id="P62", src="S39", cite="W. Lin et al. (2026)", title="DreamGuard: Efficient runtime guardrail for LLM agents via risk-aware world model", year=2026, venue="arXiv preprint, arXiv:2608.05695", role="Defense",
   agent="Tool-using LLM agents", threat="Long-horizon hazardous drift", entry=NA, obs="Each call with trajectory prefix",
   runtime=Y, context=NR, behav=Y, tool=Y, multi=Y, prov=NR, dec=Y, mit="Yes (PASS/HOLD/BLOCK)", bench=NV, fin=NR,
   metrics="Latency; risk scores", result="Immediate-hazard and prefix-risk scores fused with calibration; about 25 ms per call", limit="Learned world model; non-financial",
   q="Y Y Y NV NV NV NV NV Y P", verif="FULLY VERIFIED", prior=False),
st(id="P63", src="S40", cite="H. Liu et al. (2026)", title="SafeAgent: A runtime protection architecture for agentic systems", year=2026, venue="arXiv preprint, arXiv:2604.17562", role="Defense",
   agent="Agentic systems with multi-step workflows", threat="Prompt injection propagating through workflows", entry="Inputs and intermediate context", obs="Stateful workflow",
   runtime=Y, context=Y, behav=Y, tool=Y, multi=Y, prov=NR, dec=Y, mit=Y, bench="ASB; InjecAgent", fin=NR,
   metrics=NV, result="Improves robustness on ASB and InjecAgent; recovery confidence and policy weighting set safety-utility operating points", limit="LLM-realised operators; calibration/latency not reported (partially verified)",
   q="Y Y Y NV Y NV NV NV NV P", verif="PARTIALLY VERIFIED", prior=False),
st(id="P64", src="S41", cite="C. Yang (2026)", title="AgentTrust: Runtime safety evaluation and interception for AI agent tool use", year=2026, venue="arXiv preprint, arXiv:2605.04785", role="Defense",
   agent="Tool-using agents (shell, files, HTTP, credentials)", threat="Unsafe tool-use side effects", entry="Proposed tool call", obs="Each proposed tool call (plus session chains)",
   runtime=Y, context=NR, behav="Yes (seven chain detectors)", tool=Y, multi="Yes (session tracker; no measurable effect in ablation)", prov=NR, dec=Y, mit="Yes (allow/warn/block/review; safer alternatives)", bench="Author benchmark; 630 external scenarios", fin=NR,
   metrics="Verdict accuracy; risk-level accuracy; latency", result="95.0% verdict and 73.7% risk-level accuracy; about 1.72 ms vs. about 1.35 s for a zero-shot LLM judge; 96.7% on 630 external scenarios after rule patching", limit="Rule/analyser verdicts; no calibrated probability reported; session tracker no measurable effect (partially verified)",
   q="Y Y Y NV Y Y Y Y Y P", verif="PARTIALLY VERIFIED", prior=True),
st(id="P65", src="S42", cite="Hossain et al. (2026)", title="NEXUS: Structured runtime safety for tool-using LLM agents", year=2026, venue="arXiv preprint, arXiv:2607.19356", role="Defense",
   agent="Tool-using LLM agents", threat="Unsafe plans", entry="Proposed plan and arguments", obs="Plan (with cross-turn session state)",
   runtime=Y, context=NR, behav="Yes (partial: session manager)", tool="Yes (argument-level)", multi="Yes (partial: plan-level)", prov=NR, dec=Y, mit="Yes (allow/block/confirm/revise)", bench="Author templates; R-Judge (OOD); stress set", fin=NR,
   metrics="F1; 4-class accuracy; ECE; latency", result="F1 0.949; 4-class accuracy 0.6406 (+27.3 pp over rule-only); ECE 0.085 to 0.013 with Platt; median 0.205 ms; OOD F1 0.861 (R-Judge) and 0.881 (stress); fixed intervention costs 0/0.1/0.3/1 set loss-optimal thresholds in a rule-first cascade", limit="Plan-level; in-distribution results on author templates are upper bounds (authors); body details partially verified",
   q="Y Y Y NV Y Y Y Y Y P", verif="PARTIALLY VERIFIED", prior=True),
st(id="P66", src="S43", cite="Jackson (2025)", title="Designing a policy engine for agentic AI systems: From governance requirements to runtime enforcement", year=2025, venue="SSRN working paper, doi:10.2139/ssrn.5904104", role="Design",
   agent="Enterprise agentic systems", threat="Governance violations", entry=NA, obs="Governed action",
   runtime=Y, context=NR, behav=NV, tool=Y, multi=NV, prov=NR, dec="Yes (multi-dimensional risk score)", mit="Yes (allow/deny/sanitize/escalate)", bench=NV, fin=NR,
   metrics=NV, result="Risk score drives an enforcement state machine; reductions in unsafe actions with minimal latency reported qualitatively", limit="Unrefereed; full text not accessed",
   q="Y NV Y NV NV NV NV NV NV P", verif="PARTIALLY VERIFIED", prior=False),
st(id="P67", src="S44", cite="H.-H. Chen (2026)", title="Insuring every action: An authority frontier framework for runtime actuarial control of autonomous AI agents", year=2026, venue="arXiv preprint, arXiv:2605.25632", role="Design",
   agent="Agents taking side-effect-bearing actions", threat="Consequences of side-effecting actions", entry=NA, obs="Each priced action",
   runtime=Y, context=NR, behav=NR, tool=Y, multi=NR, prov=NR, dec="Yes (consequence pricing vs. reserve)", mit="Yes (gating)", bench=NA, fin="Yes (partial: payments, refunds as examples)",
   metrics=NA, result="Actuarial Action Interface prices consequences deterministically; Authority Frontier", limit="No estimate of adversarial induction",
   q="Y Y Y NV NA NA NA NV NA P", verif="FULLY VERIFIED", prior=False),
st(id="P68", src="S45", cite="Z. Chen et al. (2026)", title="Cordon: Semantic transactions for tool-using LLM agents", year=2026, venue="arXiv preprint, arXiv:2606.17573", role="Defense",
   agent="Tool-using LLM agents", threat="Irreversible effects; cross-step violations", entry=NA, obs="Task-level transaction",
   runtime=Y, context=NR, behav=NR, tool=Y, multi=Y, prov=NR, dec=NR, mit="Yes (staging, rollback, recovery)", bench=NV, fin=NR,
   metrics=NV, result="Exposes cross-step violations and reduces irreversible-effect failures (qualitative at abstract level)", limit="Consumes rather than produces decisions",
   q="Y Y Y NV NV NV NV NV NV P", verif="FULLY VERIFIED", prior=False),
st(id="P69", src="S46", cite="C. Zhang et al. (2026)", title="Calibration is not control: Why LLM-agent oversight needs intervention", year=2026, venue="arXiv preprint, arXiv:2606.21399", role="Analysis",
   agent="LLM-agent oversight", threat=NA, entry=NA, obs="Trajectory prefixes",
   runtime=NA, context=NA, behav=NA, tool=NA, multi="Yes (trajectory prefixes)", prov=NA, dec="Yes (intervention selection)", mit=NA, bench="ALFWorld", fin=NR,
   metrics="ECE; regret", result="Platt scaling reduces ECE 0.463 to 0.006 while regret stays at 0.318 (ALFWorld; partially verified)", limit="Analysis paper; figures via search excerpts only",
   q="Y NA Y NV Y Y Y NV Y P", verif="PARTIALLY VERIFIED", prior=False),
st(id="P70", src="S64", cite="Z. Chen, J. Chen, et al. (2025)", title="Standard benchmarks fail — Auditing LLM agents in finance must prioritize risk", year=2025, venue="arXiv preprint, arXiv:2502.15865 (position paper)", role="Analysis",
   agent="Financial LLM agents", threat="Hallucination, stale data, adversarial prompt manipulation", entry=NA, obs="Agent task outcome",
   runtime=NA, context=NA, behav=NA, tool=NA, multi=NA, prov=NA, dec=NA, mit=NA, bench="Audit of six agents on three tasks", fin=Y,
   metrics=NV, result="Accuracy/return metrics give an illusion of reliability; proposes three-level stress-testing agenda", limit="Position paper",
   q="Y Y Y NV Y NV NV NV NV P", verif="FULLY VERIFIED", prior=False),
st(id="P71", src="S65", cite="H. Jia et al. (2026)", title="FinHarness: An inline lifecycle safety harness for finance LLM agents", year=2026, venue="arXiv preprint, arXiv:2605.27333", role="Defense",
   agent="Finance LLM agents", threat="Prompt-induced unauthorised financial actions", entry="User queries; tool calls", obs="Query and tool call with cross-turn state",
   runtime=Y, context=Y, behav="Yes (partial: cross-turn drift, accumulated risk)", tool=Y, multi=Y, prov=NR, dec=Y, mit="Yes (block/approve; escalation to advanced judge)", bench="FinVault (WITHDRAWN)", fin=Y,
   metrics="ASR; benign approval; judge calls", result="ASR 38.3% to 15.0%; benign approval 41.1% to 39.3%; 4.7x fewer advanced-judge calls — all measured on the withdrawn FinVault benchmark", limit="Evaluation benchmark withdrawn; LLM judges",
   q="Y Y Y NV Y Y Y NV Y P", verif="FULLY VERIFIED", prior=True, override="LIMITED EVIDENCE",
   override_reason="All reported figures were obtained on FinVault, which has been withdrawn; they cannot serve as affirmative evidence."),
]

PRIOR_ART = ["AgentTrust", "NEXUS", "ProvenanceGuard", "FinHarness", "AgentDojo", "AgentHarm", "Progent",
             "AgentSpec", "ShieldAgent", "Task Shield", "MELON", "CaMeL", "LlamaFirewall"]
PRIOR_ART_MAP = {"AgentTrust": "P64", "NEXUS": "P65", "ProvenanceGuard": "P58", "FinHarness": "P71",
                 "AgentDojo": "P44", "AgentHarm": "P42", "Progent": "P49", "AgentSpec": "P50",
                 "ShieldAgent": "P54", "Task Shield": "P01", "MELON": "P57", "CaMeL": "P52",
                 "LlamaFirewall": "P16"}
